openapi: 3.0.0
info:
  title: Zara API
  description: Endpoints for ZARA products
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1

tags:
  - name: "productprices"

paths:
  /productprices:
    get:
      summary: ''
      tags:
        - productprices
      description: get product prices
      operationId: getProducts
      parameters:
        - name: applyDate
          in: query
          description: applyDate
          required: true
          explode: true
          example: '2020-06-14-18.30.00'
          schema:
            type: string
        - name: productId
          in: query
          description: productId
          required: true
          explode: true
          schema:
            type: integer
        - name: brandId
          in: query
          description: brandId
          required: true
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: integer
          format: int
          example: 1
        brand_id:
          type: integer
          format: int32
          example: 35455
        price_list:
          type: integer
          format: int
          example: 1
        start_date:
          type: string
        end_date:
          type: string
        price:
          type: number
          format: double
          example: 35.50
        priority:
          type: integer
          format: int
          example: 1
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string